steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/bank-anthos-ai-india/bank-of-anthos/ai-assistant:v1.1.0', '.']
images:
- 'asia-south1-docker.pkg.dev/bank-anthos-ai-india/bank-of-anthos/ai-assistant:v1.1.0'